name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  upload-artifacts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r gh-repos/Delivery_time_pred/requirements.txt

      - name: Run pipeline again to generate artifacts
        run: |
          python gh-repos/Delivery_time_pred/main.py

      - name: Upload ML model artifact
        uses: actions/upload-artifact@v3
        with:
          name: best_model
          path: gh-repos/Delivery_time_pred/models/best_model.pkl

      - name: Upload MLflow tracking directory
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-runs
          path: gh-repos/Delivery_time_pred/mlruns/
