name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: http://127.0.0.1:8081

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Start MLflow server in background
        run: |
          mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 127.0.0.1 --port 8081 &
          sleep 10

      - name: Run pipeline
        run: python Delivery_time_pred/main.py

      - name: Run tests
        run: pytest tests/

      - name: Upload MLflow run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: ./mlruns

      - name: Upload best model file
        uses: actions/upload-artifact@v4
        with:
          name: delivery-model
          path: Delivery_time_pred/models/best_model.pkl
